#!/usr/bin/env python3
"""Build the v2.1 7-arm head-to-head comparison table from the overnight sweep's
per-sample eval files (+ optional LLM-judge file). Self-contained: aggregates
EM / containment / recall / F1 straight from the per-sample rows, so it does not
depend on the (graph_v5-era) build_results_doc.py or any nested summary schema.

Inputs (under outputs/repr_learning/eval_per_family/):
  eval_<TAG>_<variant>[_locomo]_per_sample.jsonl   — one or more eval passes/arm
  judge_<TAG>_per_sample.jsonl                     — optional, adds Judge column
Output:
  docs/repr_learning_v2_1_results.md  + a console headline.

Robust to missing arms/files: tabulates whatever is present (partial sweep OK).
"""
from __future__ import annotations
import argparse, json, glob
from pathlib import Path
from collections import defaultdict, Counter

ROOT = Path(__file__).resolve().parents[2]
EVAL = ROOT / "outputs/repr_learning/eval_per_family"

ORDER = ["graph_v6_baseline", "flat_baseline", "continuous_baseline",
         "recurrent_baseline", "memorizing_baseline", "vanilla_llama",
         "vanilla_full_context"]
DISP = {"graph_v6_baseline": "graph_v6 (primary)", "flat_baseline": "flat",
        "continuous_baseline": "continuous", "recurrent_baseline": "mamba",
        "memorizing_baseline": "MT", "vanilla_llama": "vanilla (no ctx, floor)",
        "vanilla_full_context": "vanilla (full ctx, ceiling)"}
FAMS = ["biographical", "hotpot_qa", "musique", "narrative_qa", "babilong",
        "ruler_niah", "locomo"]
SCORE = {"correct": 1.0, "correct_verbose": 1.0, "incomplete": 0.5,
         "partially_wrong": 0.25, "wrong_value": 0.0, "irrelevant": 0.0,
         "no_answer": 0.0}
CATS = ["correct", "correct_verbose", "incomplete", "partially_wrong",
        "wrong_value", "irrelevant", "no_answer"]


def pct(xs):
    return 100.0 * sum(xs) / len(xs) if xs else float("nan")


def fmt(x):
    return "  —  " if x != x else f"{x:.1f}"   # NaN → dash


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", required=True, help="sweep tag (run dirs eval_<tag>_<variant>)")
    ap.add_argument("--out", type=Path, default=ROOT / "docs/repr_learning_v2_1_results.md")
    args = ap.parse_args()

    # ---- gather eval per-sample rows (all passes/arms for this tag) ----
    em = defaultdict(list); con = defaultdict(list)
    rec = defaultdict(list); f1 = defaultdict(list)
    con_fam = defaultdict(lambda: defaultdict(list))
    n_seen = defaultdict(int)
    paths = sorted(glob.glob(str(EVAL / f"eval_{args.tag}_*_per_sample.jsonl")))
    paths = [p for p in paths if "_ALL_" not in p]           # skip combined judge-input
    for p in paths:
        for line in open(p):
            try:
                r = json.loads(line)
            except json.JSONDecodeError:
                continue
            v, fam = r.get("variant"), r.get("family")
            if v is None:
                continue
            n_seen[v] += 1
            em[v].append(r.get("em", 0)); con[v].append(r.get("contain", 0))
            rec[v].append(r.get("recall", 0)); f1[v].append(r.get("f1", 0))
            con_fam[v][fam].append(r.get("contain", 0))

    # ---- optional judge ----
    jsc = defaultdict(list); jcat = defaultdict(Counter)
    jpath = EVAL / f"judge_{args.tag}_per_sample.jsonl"
    have_judge = jpath.exists()
    if have_judge:
        for line in open(jpath):
            try:
                j = json.loads(line)
            except json.JSONDecodeError:
                continue
            cat = j.get("category")
            if j.get("score") is not None and not str(cat).startswith("__FAIL__"):
                jsc[j["variant"]].append(j["score"]); jcat[j["variant"]][cat] += 1

    present = [v for v in ORDER if v in n_seen] + [v for v in n_seen if v not in ORDER]
    if not present:
        print(f"[build_table] no eval per-sample files found for tag '{args.tag}' under {EVAL}")
        return

    L = []
    L.append("# v2.1 head-to-head — graph_v6 vs baselines (overnight sweep)\n")
    L.append(f"_Auto-generated by `build_overnight_table.py` (tag `{args.tag}`) from per-sample eval files._\n")
    L.append("All arms: 274,944-float memory state (MT float-exempt), ~48M matched memory params, "
             "identical rank-16 q/v LoRA on a frozen Llama-3.2-1B, joint-trained.\n")
    L.append("- **EM** — exact match (strict). **Containment** — gold span appears (verbosity-robust). "
             "**Recall/F1** — token overlap. " +
             ("**Judge** — Gemini-3-Flash, 7-cat rubric (headline; paraphrase+verbosity robust)."
              if have_judge else "_Judge column pending (judge file not found)._") + "\n")

    # ---- headline ----
    L.append("\n## Headline (macro over all eval samples, %)\n")
    hdr = "| model | n | EM | Containment | Recall | F1 |" + (" **Judge** |" if have_judge else "")
    L.append(hdr)
    L.append("|" + "---|" * (6 + (1 if have_judge else 0)))
    def sort_key(v):
        return -pct(jsc[v]) if have_judge and jsc[v] else -pct(con[v])
    rows = sorted(present, key=sort_key)
    for v in rows:
        cell = f"| {DISP.get(v, v)} | {n_seen[v]} | {fmt(pct(em[v]))} | {fmt(pct(con[v]))} | {fmt(pct(rec[v]))} | {fmt(pct(f1[v]))} |"
        if have_judge:
            cell += f" **{fmt(pct(jsc[v]))}** |"
        L.append(cell)

    # ---- containment by family ----
    L.append("\n## Containment by family (%)\n")
    fams_present = [f for f in FAMS if any(con_fam[v].get(f) for v in present)]
    L.append("| model | " + " | ".join(f.replace("_qa", "").replace("_", " ") for f in fams_present) + " |")
    L.append("|" + "---|" * (len(fams_present) + 1))
    for v in rows:
        cells = " | ".join(fmt(pct(con_fam[v].get(f, []))) for f in fams_present)
        L.append(f"| {DISP.get(v, v)} | {cells} |")

    # ---- judge categories ----
    if have_judge:
        L.append("\n## LLM-judge category breakdown (counts)\n")
        L.append("Score map: correct/verbose=1.0, incomplete=0.5, partially_wrong=0.25, "
                 "wrong_value/irrelevant/no_answer=0.0.\n")
        L.append("| model | " + " | ".join(CATS) + " |")
        L.append("|" + "---|" * (len(CATS) + 1))
        for v in rows:
            c = jcat[v]
            L.append(f"| {DISP.get(v, v)} | " + " | ".join(str(c[k]) for k in CATS) + " |")

    args.out.write_text("\n".join(L) + "\n")
    print(f"[build_table] wrote {args.out}")
    print("\n--- headline ---")
    for v in rows:
        j = f"  Judge={fmt(pct(jsc[v]))}" if have_judge else ""
        print(f"  {DISP.get(v, v):28s} n={n_seen[v]:4d}  EM={fmt(pct(em[v]))}  "
              f"Contain={fmt(pct(con[v]))}  F1={fmt(pct(f1[v]))}{j}")


if __name__ == "__main__":
    main()
